from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 398)
        MainWindow.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 514, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_scale_maps = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_scale_maps.setFont(font)
        self.title_scale_maps.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.title_scale_maps.setObjectName("title_scale_maps")
        self.gridLayout.addWidget(self.title_scale_maps, 0, 2, 1, 1)
        self.map_scale = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.map_scale.setObjectName("map_scale")
        self.gridLayout.addWidget(self.map_scale, 0, 3, 1, 1)
        self.title_type_maps = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_type_maps.setFont(font)
        self.title_type_maps.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.title_type_maps.setObjectName("title_type_maps")
        self.gridLayout.addWidget(self.title_type_maps, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.type_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.type_3.setObjectName("type_3")
        self.horizontalLayout.addWidget(self.type_3)
        self.type_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.type_1.setObjectName("type_1")
        self.horizontalLayout.addWidget(self.type_1)
        self.type_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.type_2.setObjectName("type_2")
        self.horizontalLayout.addWidget(self.type_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 340, 651, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search.setFont(font)
        self.search.setStyleSheet("background-color: rgb(255, 146, 0);")
        self.search.setObjectName("search")
        self.gridLayout_2.addWidget(self.search, 1, 2, 1, 1)
        self.plus_postal_code = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plus_postal_code.setFont(font)
        self.plus_postal_code.setObjectName("plus_postal_code")
        self.gridLayout_2.addWidget(self.plus_postal_code, 1, 3, 1, 1)
        self.place_address = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.place_address.setObjectName("place_address")
        self.gridLayout_2.addWidget(self.place_address, 1, 1, 1, 1)
        self.reset = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("background-color: rgb(255, 146, 0);")
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 1, 4, 1, 1)
        self.title_address = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_address.setFont(font)
        self.title_address.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.title_address.setObjectName("title_address")
        self.gridLayout_2.addWidget(self.title_address, 1, 0, 1, 1)
        self.title_full_address = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_full_address.setFont(font)
        self.title_full_address.setObjectName("title_full_address")
        self.gridLayout_2.addWidget(self.title_full_address, 0, 0, 1, 1)
        self.output_full_address = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.output_full_address.setObjectName("output_full_address")
        self.gridLayout_2.addWidget(self.output_full_address, 0, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.group = QtWidgets.QButtonGroup()
        self.group.addButton(self.type_1)
        self.group.addButton(self.type_2)
        self.group.addButton(self.type_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Maps_API"))
        self.title_scale_maps.setText(
            _translate("MainWindow", "Масштаб карты"))
        self.title_type_maps.setText(_translate("MainWindow", "Вид карты"))
        self.type_3.setText(_translate("MainWindow", "Гибрид"))
        self.type_1.setText(_translate("MainWindow", "Схема"))
        self.type_2.setText(_translate("MainWindow", "Спутник"))
        self.search.setText(_translate("MainWindow", "Искать"))
        self.plus_postal_code.setText(_translate(
            "MainWindow", "Приписывать почтовый адрес"))
        self.reset.setText(_translate("MainWindow", "Сброс поиска"))
        self.title_address.setText(_translate("MainWindow", "Адрес"))
        self.title_full_address.setText(
            _translate("MainWindow", "Вывод полного адреса"))

